@startuml "ניהול חומרי למידה"
Actor User
participant GUI as "CourseNote"
database Study_Meterials as "Study_Meterials"

activate User
User->GUI: "v"
activate GUI
GUI->Study_Meterials: "v"
activate Study_Meterials
Study_Meterials->GUI: "v"
deactivate Study_Meterials
GUI->User: "v" 
deactivate GUI
deactivate User
@enduml