@startuml "צפייה במערכת שעות"
Actor User
participant GUI as "Weekly Schedule"
participant Database_Course_Schedule as "Course_Schedule"

activate User
User->GUI: "Request Weekly Schedule"
activate GUI
GUI->Database_Course_Schedule: "Query Course_Schedule for student's weekly schedule"
activate Database_Course_Schedule
Database_Course_Schedule->GUI: "Returns schedule data"
deactivate Database_Course_Schedule
GUI->User: "View schedule"
deactivate GUI


User->GUI: "Update Weekly Schedule"
activate GUI
GUI->User: "Enter new schedule details"
User->GUI: "Submit new schedule details"
GUI->Database_Course_Schedule: "Update Course_Schedule with new schedule data"
activate Database_Course_Schedule
Database_Course_Schedule->GUI: "Confirmation of update success/failure"
deactivate Database_Course_Schedule
GUI->User: "Display confirmation message"
deactivate GUI
deactivate User
@enduml