@startuml "Learning Material Management"
Actor User
participant GUI as "CourseNote"
participant Study_Meterials as "Study_Meterials"

activate User
User->GUI: "Opens the CourseNote application"
activate GUI
GUI->Study_Meterials: "Requests learning materials from Study_Meterials"
activate Study_Meterials
Study_Meterials->GUI: "Returns learning materials to CourseNote"
deactivate Study_Meterials
GUI->User: "Displays learning materials to the user" 
deactivate GUI
deactivate User
@enduml